<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="AutoCutPic.Tests\**" />
    <EmbeddedResource Remove="AutoCutPic.Tests\**" />
    <None Remove="AutoCutPic.Tests\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Magick.NET-Q8-OpenMP-x64" Version="14.17.2" />
  </ItemGroup>
</Project>
